spring:
  application:
    name: distributed-order-platform
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USERNAME:orders}
    password: ${DB_PASSWORD:orders}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-processor
      auto-offset-reset: earliest
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  kafka:
    order-created-topic: order-created

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}]"
